name: "moban-anyconfig"
organisation: "moremoban"
author: "C.W."
contact: "wangc_2011@hotmail.com"
company: "moban dev team"
version: "0.0.1"
current_version: "0.0.1"
release: "0.0.1"
copyright_year: 2020
license: mit
dependencies:
  - anyconfig
  - toml
description: "Read data of any format and any location for moban template rendering"
lint_command: make install_test lint format git-diff-check
